### ISSUE TITLE
Write EM Development 102 Class

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_external_module_development_guide#35]
Turn the Dev Class doc we have into a self-guided intro into building a REDCap Development environment with a running REDCap, Dev tools, and a tour of REDCap from an Admin's perspective. Construct it so that it is accessible to a REDCap project builder with no development skills, yet allow a developer to skip quickly to the parts germane to them. 

Crudely, follow these steps:

1. Copy https://github.com/ctsit/redcap_external_module_development_guide/blob/master/docs/development_class.md to the rc_em_dev_101.md
1. Title it "A tour through REDCap as an Admin"
1. Delete everything above "Playtime"
1. Add an intro describing the content. Note basic prereqs like the 'REDCap External Module Development for REDCap Admins and Developers' and RC EM DEV Guide 101
1. Expand 'Playtime' into 5-8 sections highlighting import features of REDCap from an Admins perspective. Use annotated images in each section to provide a visual guide. Annotate images with Skitch. Make sure to cover external module installation and REDCap Repo exploration (everyone).

**Comment by tlstoffs** [comment]
- Access the Control Center > Browse Users. Look at the accounts that the installer made for you: 

<img width="286" alt="Screen Shot 2020-09-08 at 10 36 09 AM" src="https://user-images.githubusercontent.com/21062119/92499821-52057a80-f1ca-11ea-84b5-079654a28b8e.png">

You can also use this to find any specific REDCap user:

<img width="769" alt="Screen Shot 2020-09-08 at 10 37 07 AM" src="https://user-images.githubusercontent.com/21062119/92499952-811bec00-f1ca-11ea-92e8-b1f2a104ed89.png">

Click on the name /user to access their account, see which projects they have access to, and to suspend or delete their account:

<img width="690" alt="Screen Shot 2020-09-08 at 10 43 21 AM" src="https://user-images.githubusercontent.com/21062119/92500175-c5a78780-f1ca-11ea-86bd-9b89e0e44189.png">


- Access the Control Center > General Configuration:

<img width="282" alt="Screen Shot 2020-09-08 at 10 44 31 AM" src="https://user-images.githubusercontent.com/21062119/92500439-26cf5b00-f1cb-11ea-9e46-2f626f7e856d.png">

The Other System Settings section is important for REDCap Admins:

<img width="726" alt="Screen Shot 2020-09-08 at 10 55 57 AM" src="https://user-images.githubusercontent.com/21062119/92500562-4f575500-f1cb-11ea-85d5-600e4570a776.png">

<img width="598" alt="Screen Shot 2020-09-08 at 10 49 51 AM" src="https://user-images.githubusercontent.com/21062119/92500810-b412af80-f1cb-11ea-9a64-5f6c7a62eb69.png">

- Access the Control Center > Configuration Check:

<img width="261" alt="Screen Shot 2020-09-08 at 12 08 24 PM" src="https://user-images.githubusercontent.com/21062119/92501086-1370bf80-f1cc-11ea-8ee7-cbc2e45eea75.png">

If your installation is set up correctly, everything should be highlighted in green here. If there is an issue, the problem will be highlighted in red.

<img width="701" alt="Screen Shot 2020-09-08 at 10 50 24 AM" src="https://user-images.githubusercontent.com/21062119/92501287-5763c480-f1cc-11ea-8885-bb4f06cde786.png">

- Access the Control Center > User Settings:

<img width="267" alt="Screen Shot 2020-09-08 at 10 51 22 AM" src="https://user-images.githubusercontent.com/21062119/92501411-811ceb80-f1cc-11ea-8d09-82e92a3be25c.png">

**Comment by ChemiKyle** [comment]
Addressed by #36
